HirentWeb2022/Controllers/PartialController.cs
using DocumentFormat.OpenXml.Spreadsheet;
using HirentWeb2022.Models;
using HirentWeb2022.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HirentWeb2022.Controllers
{
    public class PartialController : Controller
    {
        public static string RemoveUnicode(string text)
        {
            string[] arr1 = new string[] { "á", "à", "ả", "ã", "ạ", "â", "ấ", "ầ", "ẩ", "ẫ", "ậ", "ă", "ắ", "ằ", "ẳ", "ẵ", "ặ",
    "đ",
    "é","è","ẻ","ẽ","ẹ","ê","ế","ề","ể","ễ","ệ",
    "í","ì","ỉ","ĩ","ị",
    "ó","ò","ỏ","õ","ọ","ô","ố","ồ","ổ","ỗ","ộ","ơ","ớ","ờ","ở","ỡ","ợ",
    "ú","ù","ủ","ũ","ụ","ư","ứ","ừ","ử","ữ","ự",
    "ý","ỳ","ỷ","ỹ","ỵ",};
            string[] arr2 = new string[] { "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
    "d",
    "e","e","e","e","e","e","e","e","e","e","e",
    "i","i","i","i","i",
    "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
    "u","u","u","u","u","u","u","u","u","u","u",
    "y","y","y","y","y",};
            for (int i = 0; i < arr1.Length; i++)
            {
                text = text.Replace(arr1[i], arr2[i]);
                text = text.Replace(arr1[i].ToUpper(), arr2[i].ToUpper());
            }
            return text;
        }
        public ActionResult Search(string keyword)
        {
            var db = new HirentEntities();
            AutoCompleteSearch autoCompleteSearch = new AutoCompleteSearch();
            List<tb_Product> lstProduct = new List<tb_Product>();
            var getMaincate = db.tb_CategoryMain.ToList().Where(p => RemoveUnicode(p.MainCateName.ToLower()).Contains(RemoveUnicode(keyword.ToLower()))).Select(p => p).ToList();
            if (getMaincate != null)
            {
                foreach (var item in getMaincate)
                {
                    ProductCateSearch ProductCateSearch = new ProductCateSearch();
                    ProductCateSearch.Name = item.MainCateName;
                    ProductCateSearch.url = "/productcate?MainCateID=" + item.MainCateID;
                    autoCompleteSearch.productCateSearches.Add(ProductCateSearch);
                    //Addproduct
                    //var lsttb_ProductCategorySelection = db.tb_ProductCategorySelection.Where(m => m.ProductMainCate == item.MainCateID).ToList();
                    //foreach(var it in lsttb_ProductCategorySelection)
                    //{
                    //    var pd = db.tb_Product.Find(it.ProductId);
                    //    if (pd != null)
                    //    {
                    //        lstProduct.Add(pd);
                    //    }
                    //}
                    //lstProduct = lstProduct.Take(5).ToList();
                }
            }
            var getCateSub1 = db.tb_CategorySub1.ToList().Where(p => RemoveUnicode(p.SubCate1Name.ToLower()).Contains(RemoveUnicode(keyword.ToLower()))).Select(p => p).ToList();
            if (getCateSub1 != null)
            {
                foreach (var item in getCateSub1)
                {
                    ProductCateSearch ProductCateSearch = new ProductCateSearch();
                    ProductCateSearch.Name = item.SubCate1Name;
                    ProductCateSearch.url = "/productcate?ProductSubCate1=" + item.SubCate1ID;
                    autoCompleteSearch.productCateSearches.Add(ProductCateSearch);

                }
            }
            var getCateSub2 = db.tb_CategorySub2.ToList().Where(p => RemoveUnicode(p.SubCate2Name.ToLower()).Contains(RemoveUnicode(keyword.ToLower()))).Select(p => p).ToList();

            if (getCateSub2 != null)
            {
                foreach (var item in getCateSub2)
                {
                    ProductCateSearch ProductCateSearch = new ProductCateSearch();
                    ProductCateSearch.Name = item.SubCate2Name;
                    ProductCateSearch.url = "/productcate?ProductSubCate2=" + item.SubCate2ID;
                    autoCompleteSearch.productCateSearches.Add(ProductCateSearch);
                }
            }
            //Nếu ko có danh mục thì lấy sản phẩm dựa theo search

            if (autoCompleteSearch.productCateSearches.Count == 0)
            {
                lstProduct = db.tb_Product.ToList().Where(m => RemoveUnicode(m.ProductName.ToLower()).Contains(RemoveUnicode(keyword.ToLower()))).ToList();
            }

            if (lstProduct != null)
            {
                foreach (var item in lstProduct)
                {
                    ProductSeacch productSeacch = new ProductSeacch();
                    productSeacch.Name = item.ProductName;
                    productSeacch.url = "/ProductDetail?productID=" + item.ProductID;
                    productSeacch.Images = item.ProductAvatar;
                    autoCompleteSearch.productSearches.Add(productSeacch);
                }
            }
            autoCompleteSearch.productCateSearches = autoCompleteSearch.productCateSearches.GroupBy(m => m.Name).SelectMany(f => f.Take(1)).ToList();
            return PartialView(autoCompleteSearch);
        }
        // GET: Partial
        public ActionResult Menutop()
        {

            var getlang = Session["Lang"];
            if (getlang == null)
            {
                getlang = "vi";
                Session["Lang"] = "vi";
            }
            ViewBag.lang = getlang;
            using (var db = new HirentEntities())
            {
                ViewBag.tb_CategoryMain = db.tb_CategoryMain.OrderBy(m=>m.Sort).ToList();
            }
            return PartialView();
        }
        public ActionResult Footer()
        {
            var getlang = Session["Lang"];
            if (getlang == null)
            {
                getlang = "vi";
                Session["Lang"] = "vi";
            }
            ViewBag.lang = getlang;
            return PartialView();
        }

        public ActionResult MenuSub1(int MainCateID)
        {
            var getlang = Session["Lang"];
            if (getlang == null)
            {
                getlang = "vi";
                Session["Lang"] = "vi";
            }
            ViewBag.lang = getlang;
            using (var db = new HirentEntities())
            {
                ViewBag.tb_CategorySub1 = db.tb_CategorySub1.Where(m => m.MainCateID == MainCateID).ToList();
            }
            return PartialView();
        }
        public ActionResult MenuMobileSub1(int MainCateID)
        {
            var getlang = Session["Lang"];
            if (getlang == null)
            {
                getlang = "vi";
                Session["Lang"] = "vi";
            }
            ViewBag.lang = getlang;
            using (var db = new HirentEntities())
            {
                var model = db.tb_CategorySub1.Where(m => m.MainCateID == MainCateID).ToList();
                return PartialView(model);
            }

        }
        public ActionResult MenuSub2(int SubCate1ID)
        {
            var getlang = Session["Lang"];
            if (getlang == null)
            {
                getlang = "vi";
                Session["Lang"] = "vi";
            }
            ViewBag.lang = getlang;
            using (var db = new HirentEntities())
            {
                ViewBag.tb_CategorySub2 = db.tb_CategorySub2.Where(m => m.SubCate1ID == SubCate1ID).ToList();
            }
            return PartialView();
        }
        public void setLanguage(string lang)
        {
            if (lang == "vi")
                Session["Lang"] = "vi";
            else
                Session["Lang"] = "en";
        }
        public ActionResult LoadMenu()
        {
            var getlang = Session["Lang"];
            if (getlang == null)
            {
                getlang = "vi";
                Session["Lang"] = "vi";
            }
            ViewBag.lang = getlang;

            HttpCookie reqCookies = Request.Cookies["HirentLogin"];
            if (reqCookies != null)
            {
                ViewBag.UserName = reqCookies["username"].ToString();
            }
            return PartialView();
        }

        public ActionResult Helper()
        {
            return PartialView();
        }

        public string RemoveMark(string mark)
        {
            return mark.Replace("?", "").Replace("!", "");
        }

        public double Mathword(string question, string keyword)
        {
            //Loại bỏ ?,!
            question = RemoveMark(question);
            keyword = RemoveMark(keyword);
            // Tách câu thành các từ
            string[] questionWords = question.Split(' ');
            string[] keywordWords = null;

            keywordWords = keyword.Split(' ');
            int matchCount = 0;

            // So sánh từng từ
            foreach (var word in questionWords)
            {
                if (Array.Exists(keywordWords, element => RemoveUnicode(element.ToLower()) == RemoveUnicode(word.ToLower())))
                {
                    matchCount++;
                }
            }

            // Tính toán độ tương đồng
            double similarity = (double)matchCount / keywordWords.Length;

            // In ra kết quả
            if (similarity >= 0.5)
            {
                Console.WriteLine("Câu hỏi tương đồng với câu khóa.");
            }
            else
            {
                Console.WriteLine("Câu hỏi không tương đồng với câu khóa.");
            }
            return similarity;
        }

        [HttpPost]
        //public ActionResult Botanswer(string question)
        //{
        //    List<VM_Chatbot> lstVmChatbot = new List<VM_Chatbot>();
        //    using (HirentEntities db = new HirentEntities())
        //    {
        //        var lstKeywords = db.tb_Chatbot.ToList();
        //        foreach (var word in lstKeywords)
        //        {

HirentWeb2022/Views/Partial/Botanswer.cshtml
<div class="helper_content_ai">
    @{
        if (Model != null)
        {
            if (!string.IsNullOrEmpty(Model.Answer))
            {
                <span> @Model.Answer</span>
            }
            else
            {
                <span>Xin lỗi, tôi không thể trả lời...</span>
            }
        }

    }
</div>

HirentWeb2022/Views/Partial/ChangePassword.cshtml
<div class="from_register_container">
    <div class="from_register">
        @{
            var user = (HirentWeb2022.Models.tb_Customer)ViewBag.Info;


        }
        @if (user != null)
        {
            <div class="form_register_title">
                @(ViewBag.lang == "vi"? "Thay đổi mật khẩu" : "Change password")
            </div>
            <form>
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">@(ViewBag.lang == "vi"? "Password hiện tại" : "Current password")</label>
                    <div class="col-sm-10">
                        <input value="@user.CustomerID" type="hidden" id="txtCustomerID" />
                        <input type="text" class="form-control" id="txtCurrentpassword" placeholder="@(ViewBag.lang == "vi"? "Password hiện tại" : "Current password")">
                    </div>


                </div>
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">@(ViewBag.lang == "vi"? "Password mới" : "New password")</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="txtNewpassword" placeholder="@(ViewBag.lang == "vi"? "Password mới" : "New password")">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">@(ViewBag.lang == "vi"? "Xác nhận mật khẩu" : "Confirm password")</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="txtConfirmpassword" placeholder="@(ViewBag.lang == "vi"? "Xác nhận mật khẩu" : "Confirm password")">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12 text-right">
                        <button onclick="updateInfo('@user.CustomerID')" type="button" class="btn btn-primary">@(ViewBag.lang == "vi"? "Đổi mật khẩu" : "Submit")</button>
                    </div>
                </div>
            </form>
        }

    </div>
</div>


<script>
    let updateInfo = (id) => {
        var currentPassword = $("#txtCurrentpassword").val();
        var newPassword = $("#txtNewpassword").val();
        var confirmPasswoed = $("#txtConfirmpassword").val();
        if (currentPassword == '' || newPassword == '' || confirmPasswoed==''   ) {
            if ('@ViewBag.lang' === 'vi')
            {
                  showToast("Thông báo", "Mật khẩu không được để trống!",1);
            }
            else
            {
                  showToast("Message", "Password cannot be empty!", 1);
            }
            $("#txtCurrentpassword").focus();

            return;
        }
        if (newPassword != confirmPasswoed)
        {
            if ('@ViewBag.lang' === 'vi')
            {
                showToast("Thông báo", "Mật khẩu mới không trùng nhau!",1);
            }
            else
            {
                showToast("Message", "The two passwords do not match!", 1);
            }

            return;
        }

        var pr = {
            CustomerID: $("#txtCustomerID").val(),
            currentPassword: currentPassword
        }
                $.ajax({
            url: '/Partial/Checkpassword',
            type: "POST",
            dataType: 'html',
            data: pr,
            success: function (data, status, xhr) {
                if (data === 'True')
                {
                     if ('@ViewBag.lang' === 'vi')
                     {
                         showToast("Thông báo", "Mật khẩu hiện tại không đúng!", 1);
                         return;
                     }
                
                }
            },
            error: function (xhr, status, error) {
                alert(status);
            }
                }); 

        var pr2 = {
            CustomerID: $("#txtCustomerID").val(),
            newPassword: newPassword
        }
        $.ajax({
            url: '/Partial/UpdatePasswod',
            type: "POST",
            dataType: 'html',
            data: pr2,
            success: function (data, status, xhr) {
                if (data === 'True') {
                     if ('@ViewBag.lang' === 'vi')
                    {
                         showToast("Thông báo", "Cập nhật thành công!",1);
                    }
                    else
                    {
                         showToast("Message", "Update successful!", 1);
                    }
                    location.reload();
                }
            },
            error: function (xhr, status, error) {
                alert(status);
            }
        });
    }
    let selectGender = 1;
    function rad(id) {
        selectGender = id;
    }

</script>

HirentWeb2022/Views/Partial/ChangeProvinces.cshtml
@{
    foreach (HirentWeb2022.Models.district dt in Model)
    {
        if (ViewBag.lang == "vi")
        {
            <option value="@dt.code">@dt.full_name</option>
        }
        else
        {
            <option value="@dt.code">@dt.full_name_en</option>
        }
    }
}

<script>
  
   
</script>

HirentWeb2022/Views/Partial/ChangeeDistricts.cshtml
@{
    foreach (HirentWeb2022.Models.ward dt in Model)
    {
        if (ViewBag.lang == "vi")
        {
            <option value="@dt.code">@dt.full_name</option>
        }
        else
        {
            <option value="@dt.code">@dt.full_name_en</option>
        }
    }
}

HirentWeb2022/Views/Partial/Footer.cshtml
<footer id="footer" class="section section-grey">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- footer widget -->
            <div class="col-md-4 col-sm-6 col-xs-6">
                <div class="footer">
                    <!-- footer logo -->
                    <!-- <div class="footer-logo">
                        <a class="logo" href="#">
                            <img src="./img/SiYoSa-Logo.png" alt="">
                        </a>
                    </div> -->
                    <h3 class="footer-header" >Thông tin liên hệ</h3>
                    <!-- /footer logo -->

                    <p>Số ĐKKD: 0312776486 - Ngày cấp: 13/05/2014, được sửa đổi lần thứ 6, ngày 23/05/2016. </p>
                    <p>Cơ quan cấp: Sở Kế hoạch và Đầu tư TPHCM.</p>
                    <p>Địa chỉ: Tòa nhà Nam Anh, số 41, Đường 41, Phường Thảo Điền, Quận 2, Tp.HCM.</p>
                    <p>Email: <u>lienhe@hirent.vn</u> </p>


                    <!-- footer social -->
                    <ul class="footer-social">
                        <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-pinterest"></i></a></li>
                    </ul>
                    <!-- /footer social -->
                </div>
            </div>
            <!-- /footer widget -->
            <!-- footer widget -->
            <div class="col-md-2 col-sm-6 col-xs-6">
                <div class="footer">
                    <h3 class="footer-header">HỖ TRỢ KHÁCH HÀNG</h3>
                    <ul class="list-links">
                        <li><a href="#">Trung tâm trợ giúp</a></li>
                        <li><a href="#">An toàn mua bán</a></li>
                        <li><a href="#">Quy định cần biết</a></li>
                        <li><a href="#">Liên hệ hỗ trợ</a></li>
                        <li><a href="#">Login</a></li>
                    </ul>
                </div>
            </div>
            <!-- /footer widget -->

            <div class="clearfix visible-sm visible-xs"></div>

            <!-- footer widget -->
            <div class="col-md-2 col-sm-6 col-xs-6">
                <div class="footer">
                    <h3 class="footer-header">VỀ CHÚNG TÔI</h3>
                    <ul class="list-links">
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Quy chế hoạt động</a></li>
                        <li><a href="#">Chính sách bán hàng</a></li>
                        <li><a href="#">Hệ thống kiểm định</a></li>
                    </ul>
                </div>
            </div>
            <!-- /footer widget -->
            <!-- footer subscribe -->
            <div class="col-md-2 col-sm-6 col-xs-6">
                <div class="footer">
                    <h3 class="footer-header">ĐĂNG KÝ NHẬN TIN KHUYẾN MÃI</h3>
                    <p>Thông tin của bạn sẽ được bảo mật tuyệt đối và bạn có thể hủy đăng ký bất cứ lúc nào..</p>

                    <div class="form-group">
                        <input class="input" placeholder="Enter Email Address">
                    </div>
                    <button class="primary-btn">ĐĂNG KÝ</button>

                </div>
            </div>
            <!-- /footer subscribe -->
        </div>
        <!-- /row -->
        <!-- row -->
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <!-- footer copyright -->
                <div class="footer-copyright">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright ©
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | 2018
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
                <!-- /footer copyright -->
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</footer>

<div>
    @Html.Action("Helper","Partial")
</div>

HirentWeb2022/Views/Partial/MenuMobileSub1.cshtml
@if (Model != null)
{
    foreach (HirentWeb2022.Models.tb_CategorySub1 item in Model)
    {
        <li>
            <a href="productcate?ProductSubCate1=@item.SubCate1ID">
                @item.SubCate1Name
            </a>
        </li>
    }
}

HirentWeb2022/Views/Partial/MenuSub1.cshtml
<div class="custom-menu">
    <div class="row row-eq-height">
        @if (ViewBag.tb_CategorySub1 != null)
        {
            foreach (HirentWeb2022.Models.tb_CategorySub1 item in ViewBag.tb_CategorySub1)
            {
                <div class="col-md-3" style="margin-top:18px;min-height:250px;">
                    <ul class="list-links listfirst">
                        <li>
                            <a href="productcate?ProductSubCate1=@item.SubCate1ID">
                                @if (ViewBag.lang == "vi")
                                {
                                    <h3 class="list-links-title">@item.SubCate1Name</h3>
                                }
                                else
                                {
                                    <h3 class="list-links-title">@item.Language</h3>
                                }
                            </a>
                        </li>
                    </ul><hr class="hidden-md hidden-lg">
                      @Html.Action("MenuSub2", "Partial", new { SubCate1ID = item.SubCate1ID })
                </div>
              
            }

        }
    </div>
    @*<div class="row hidden-sm hidden-xs"><div class="col-md-12"><hr><a class="banner banner-1" href="#"><img src="../image_banner/banner_maincate_default.jpg" alt=""></a></div></div>*@
</div>

HirentWeb2022/Views/Partial/MenuSub2.cshtml
<ul class="list-links">
    @if (ViewBag.tb_CategorySub2 != null)
    {
        foreach (HirentWeb2022.Models.tb_CategorySub2 item in ViewBag.tb_CategorySub2)
        {

            <li>
                <a href="productcate?ProductSubCate2=@item.SubCate2ID">
                    @if (ViewBag.lang == "vi")
                    {
                        @item.SubCate2Name
                    }
                    else
                    {
                        @item.Language
                    }
                </a>
            </li>
        }
    }
</ul>
<hr class="hidden-md hidden-lg">

HirentWeb2022/Views/Partial/Userinfor.cshtml
<div class="from_register_container">
    <div class="from_register">
        @{ 
            var user = (HirentWeb2022.Models.tb_Customer)ViewBag.Info;
        }
        <div class="form_register_title">
            @(ViewBag.lang == "vi"? "Thông tin tài khoản" : "Account Info")
        </div>
        <hr />  
        <form class="">
            <div class="form-group row">
                <label style=" top: 5px;" for="inputEmail3" class="col-sm-2 col-form-label">@(ViewBag.lang == "vi"? "Họ tên" : "Full name")</label>
                <div class="col-sm-10 formninput">
                    <input value="@user.CustomerID" type="hidden" id="txtCustomerID" />
                    <input type="text" value="@user.FirstName" class="form-control" id="txtFirstName" placeholder="@(ViewBag.lang == "vi"? "Họ tên" : "Full name")">
                    <i class="fa fa-user"></i>
                </div>
            </div>
            <div class="form-group row">
                <label style=" top: 5px;" for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10 formninput">
                    <input type="email" class="form-control" value="@user.Email" id="txtEmail" placeholder="Email">
                    <i class="fa fa-envelope"></i>
                </div>
            </div>

            <div class="form-group row">
                <label style=" top: 5px;" for="inputPassword3" class="col-sm-2 col-form-label"> @(ViewBag.lang == "vi"? "Điện thoại" : "Phone")</label>
                <div class="col-sm-10 formninput">
                    <input type="text" class="form-control" id="txtPhone" value="@user.Phone" placeholder="@(ViewBag.lang == "vi"? "Điện thoại" : "Phone")">
                    <i class="fa fa-phone"></i>
                </div>
            </div>

            <div class="form-group row">
                <label style=" top: 5px;" for="inputPassword3" class="col-sm-2 col-form-label"> @(ViewBag.lang == "vi"? "Ngày sinh" : "Birthday")</label>
                <div class="col-sm-10 formninput">
                    <input type="text" class="form-control" value="@(user.Birthday.HasValue? user.Birthday.Value.ToShortDateString():"")" id="txtBirthday" placeholder="@(ViewBag.lang == "vi"? "Ngày sinh" : "Birthday")">
                    <i class="fa fa-calendar"></i>
                </div>
            </div>
            <div class="form-group row">
                <label style=" top: 5px;" for="inputPassword3" class="col-sm-2 col-form-label"> @(ViewBag.lang == "vi"? "Địa chỉ" : "Address")</label>
                <div class="col-sm-10 formninput">
                    <input disabled style="width:80%;float:left" type="text" class="form-control" value="@(ViewBag.Address!=null? ViewBag.Address.Address:"")" id="txtAddress" placeholder="@(ViewBag.lang == "vi"? "Địa chỉ" : "Address")">
                    <i class="fa fa-map-marker"></i>
                    <div class="addAddress">
                        <a class="btn btn-sm " onclick="addDress()"> @(ViewBag.lang == "vi"? "Thêm địa chỉ" : "Add address")</a>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12 text-right">
                    <button onclick="updateInfo()" type="button" class="btn btngreen">@(ViewBag.lang == "vi"? "Cập nhật" : "Update")</button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    let addDress = () => {
        $("#modalAddress").modal("toggle");
    }
    const updateInfo = () => {
        var param = {
            CustomerID: $("#txtCustomerID").val(),
            FirstName: $("#txtFirstName").val(),
            Email: $("#txtEmail").val(),
            Phone: $("#txtPhone").val(),
            Birthday: $("#txtBirthday").val(),
            Address: $("#txtAddress").val()
        }
        $.ajax({
            url: '/Partial/UpdateUserInfo',
            type: "POST",
            dataType: 'html',
            data: param,
            success: function (data, status, xhr) {
                if (data === 'True') {
                     if ('@ViewBag.lang' === 'vi')
 {
                         showToast("Thông báo", "Cập nhật thành công!",1);
 }
 else
 {
       showToast("Message", "Update successful!", 1);
}
                    location.reload();
                }
            },
            error: function (xhr, status, error) {
                alert(status);
            }
        });
    }
    let selectGender = 1;
    function rad(id) {
        selectGender = id;
    }
</script>
@Html.Action("CustomerAddressInfo", "Partial")
<script>
    loadDanhsachdiachi()
    $('.tab2').hide();
    function loadDanhsachdiachi() {
        $.ajax({
            url: '/Order/LoadListAddrress',
            dataType: 'html',
            type: "GET",
            async: false,
            success: function (data, status, xhr) {
                $("#tbody").html(data);
            },
            error: function (xhr, status, error) {
                alert(status);
            }
        });
    }
    function themdiachi() {
        $("#txtcustomerid2").val(0)
        $(".tab1").hide();
        $(".tab2").show();
        $("#txtName2").val('');
        $("#txtAddress2").val('');
        $("#txtPhone2").val('');
        changeProvinces();
    }
    function insertHuyAdress() {
        $(".tab1").show();
        $(".tab2").hide();
    }
    function insertAdress() {
        if ($("#slDistricts").val() == null) {
            alert("Vui lòng nhập thông tin địa chỉ");
            return;
        }
         if ($("#slWards").val() == null) {
             alert("Vui lòng nhập thông tin địa chỉ");
             return;
         }
         var param = {
             "ID": $("#txtcustomerid2").val(),
         "CustomerID": '@ViewBag.CustomerID',
         "Address": $("#txtAddress2").val(),
         "FullName": $("#txtName2").val(),
         "PhoneNumber": $("#txtPhone2").val(),
             "provinces": $("#slProvinces").val(),
             "districts": $("#slDistricts").val(),
             "wards": $("#slWards").val(),
     }
     $.ajax({
         url: '/Order/InsertAdress',
         dataType: 'html',
         data:param,
         type: "POST",
         async: false,
         success: function (data, status, xhr) {
             loadDanhsachdiachi();
             $(".tab1").show();
             $(".tab2").hide();
              LoadMacDinh('@ViewBag.CustomerID')
         },
         error: function (xhr, status, error) {
             alert(status);
         }
     });

    }

     function LoadMacDinh() {
      var param = {
         "CustomerID": '@ViewBag.CustomerID',
     }
     $.ajax({
         url: '/Order/LoadMacDinh',
         dataType: 'html',
         data:param,
         type: "POST",
         async: false,
         success: function (data, status, xhr) {
             $("#txtAddress").val(data)
         },
         error: function (xhr, status, error) {
             alert(status);
         }
     });
 }
</script>
<style>
   @@media (min-width: 768px) {
    .modal-dialog {
        width: 669px;
        margin: 30px auto;
    }
}
</style>